### PR TITLE
Add classifier support for ArtifactPromotionPlugin

### PR DESCRIPTION
**Pull request by farkasmate**
Hi,

The ArtifactPromotionPlugin currently only supports promoting of the primary artifact. To handle secondary artifacts the 'classifier' coordinate needs to be specified.

I've created a Jira issue for this feature: https://issues.jenkins-ci.org/browse/JENKINS-29623

I believe it's a small change and I've tested it as much as I could. Please consider merging it to the mainline.

Cheers,
Mate

### CODE REVIEW

**Comment by JakeStoeffler** [comment]
I have to say I've been using @farkasmate's feature here and it works really well.  Can we see about getting this merged?

**Comment by hcguersoy** [comment]
Hi,

thanks proving this PR -  I'll check it as soon as possible and give feedback.

**Comment by hcguersoy** [comment]
Hi Mate,

I've pulled and tested the changes locally.

Unfortunately there seems to be a problem: the changes causes the plugin not to be able to pull any artifact, regardless using a classifier or not.
Here is the error log (using no classifier but the same with):

```
Used promoter class: org.jenkinsci.plugins.artifactpromotion.NexusOSSPromotor
Local repository path: [/Users/guersoy/workspaces/git/artifact-promotion-plugin/work/jobs/test-simple/workspace/target/local-repo]
Started with promotion
Get Artifact and corresponding POM
Downloading: http://192.168.56.12:8081/nexus/content/repositories/candidates/hgu/testproject/0.4.1/bmg-testproject-0.4.1

Something has gone wrong and the transfer has failed: Could not find artifact hgu:bmg-testproject::0.4.1 in stagingrepo (http://192.168.56.12:8081/nexus/content/repositories/candidates/)
Could not resolve artifact: Could not find artifact hgu:bmg-testproject::0.4.1 in stagingrepo (http://192.168.56.12:8081/nexus/content/repositories/candidates/)
Promotion could not be executed
org.jenkinsci.plugins.artifactpromotion.exception.PromotionException: Could not fetch artifacts for promotion
    at org.jenkinsci.plugins.artifactpromotion.NexusOSSPromoterClosure.promote(NexusOSSPromoterClosure.java:83)
    at org.jenkinsci.plugins.artifactpromotion.RemotePromoter.call(RemotePromoter.java:34)
    at org.jenkinsci.plugins.artifactpromotion.RemotePromoter.call(RemotePromoter.java:14)
    at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
    at org.jenkinsci.plugins.artifactpromotion.NexusOSSPromotor.callPromotor(NexusOSSPromotor.java:62)
    at org.jenkinsci.plugins.artifactpromotion.ArtifactPromotionBuilder.perform(ArtifactPromotionBuilder.java:233)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
    at hudson.model.Build$BuildExecution.build(Build.java:199)
    at hudson.model.Build$BuildExecution.doRun(Build.java:160)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:533)
    at hudson.model.Run.execute(Run.java:1745)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
Promotion could not be executed: Could not fetch artifacts for promotion
Build step 'Single Artifact Promotion' marked build as failure
Finished: FAILURE
```

BTW, I've upgraded today the POM to Jenkins 1.580 but this should make no difference.

**Comment by farkasmate** [comment]
Thank you for the feedback. I'll check what's going on before the weekend and give an update.

Mate

**Comment by hcguersoy** [comment]
Please be are that I have released a new version today with support for the jobdsl-plugin.

I would consider you make the few changes to make your pr compatible with the jobdsl-supoort.

**Comment by farkasmate** [comment]
The root of the PromotionException was changing onto a different DefaultArtifact constructor which made the artifact extension parameter mandatory. Now it's optional again.

I've also added classifier support for the jobdsl extension, but haven't tested those changes.

**Comment by hcguersoy** [comment]
Hi Mate,

thanks, I'll test it hopefully in few days and merge then.

**Comment by stnor** [comment]
Hi guys. How's this coming along? I have need for this feature too asap.
Thanks!

**Comment by hcguersoy** [comment]
Hi Mate,

sorry for my very late feedback.
I've tested it and I've one point on it which we should discuss:
Then the deletion is not disabled and you define a classifier the whole version gets deleted, not only the defined artifact (aid:gid:classifier:version). So this is IMHO an unexpected behavior.
That we can do? 
* selective deletion of only this classified artifact
* documenting the behavior and adding a warning hint in the job configuration 
* enforcing the skip of deletion 

I would prefer the latest one. The first one is IMHO not easy to implement as Nexus API doesn't provide a way to delete n a granular way.

**Comment by farkasmate** [comment]
Hi,

You're right. Thanks for catching the flaw.
I can take a look at it next week, when I'm back to home.

Cheers,
Mate

**Comment by hcguersoy** [comment]
OK then.

Another one would be to skip always the deletion by default but let the user decide him/herself - we've still document this in that case.

**Comment by farkasmate** [comment]
Hi,

Finally I've managed to take a look.

Yes, deletion API is not granular, all artifacts or none.
I'd go with "skip by default" and document the change as well as the unexpected behaviour.

If it's fine with you do it.
Where to update the code? Update only the default value in config.jelly?
Where to document? README only or README and help next to the option?

Cheers,
Mate

**Comment by hcguersoy** [comment]
Hi @farkasmate,

yes, I would change the default value in the jelly file and document it both in the README, in the inline help (accessed with the help icon) and the hint, too.

**Comment by farkasmate** [comment]
Hi,

It's perfect.
Do you want me to make that change and send a new pull request? Or do you want to handle it?

Cheers,
Mate

**Comment by hcguersoy** [comment]
Hi Mate,

I would prefer if you could code whose final steps :-)

**Comment by farkasmate** [comment]
Sure, I can send an updated pull request next week.

**Comment by farkasmate** [comment]
I was so wrong about last week, sorry.
I've updated the PR with the discussed documentation.

Merry Christmas.

**Comment by hcguersoy** [comment]
Hello Mate,

looks fine - I'll do some final tests and build a release on on of the upcoming days.

Thanks for your contribution and merry Christmas.

**Pull request merged**
