### PR TITLE
Support for Pipelines

### PR DESCRIPTION
**Pull request by JulianSauer**
Hey,

I've added support for executing promotions from within a Pipeline script (see Readme for an example).

I had to update quite a few things which is why some files changed although they are not directly related to the new feature. I've tested it locally using both - the normal UI configuration as well as from within a script - and it seems to run fine. The updated version of this plugin is also being used on our Jenkins for about a week without issues.

Greetings
Julian

### CODE REVIEW

**Comment by hcguersoy** [comment]
Thank you @JulianSauer , I'll test it and merge if everything works fine.

**Comment by rbjorklin** [comment]
@hcguersoy have you had a chance to review this? I'm also interested in this functionality.

**Comment by hcguersoy** [comment]
Sorry, not yet :-(

If you're able to build the plugin out of the branch and test it a feedback would be very welcome.

**Comment by hcguersoy** [comment]
Just 4 information, I've started integrating this PR into master, but running in several problems (as usual then working with Jenkins) due to different plugin dependencies etc.

**Pull request merged**
